version: '3'
services:
    mongodb:
        container_name: "mongo-conteiner"
        image: mongo
        environment: 
            - MONGO_DATA_DIR=data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        volumes:
            - ./mongo-data:/data/db
        restart: always

    elasticsearch:
        container_name: "elasticsearch-conteiner"
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        environment:
            - node.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        restart: always
  
volumes:
    esdata:
        driver: local
